# configure install options
configure_homebrew: true
configure_dock: true
configure_iterm: true
configure_dotfiles: false
configure_config: false
configure_keyboard: true

# geerlingguy.mac.homebrew role config
homebrew_installed_packages:
  - git
  - go
  - neovim
  - node
  - openssl
  - ripgrep
  - sqlite
  - tmux
  - zsh

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-versions

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - dropbox
  - firefox
  - google-chrome
  - iterm2
  - keepassxc
  - obsidian
  - sequel-ace
  - spotify
  - sublime-text

# geerlingguy.mac.dock role config
dockitems_remove:
  - 'App Store'
  - FaceTime
  - Messages
  - Music
  - News
  - Podcasts
  - TV

dockitems_persist:
  - name: iTerm
    path: "/Applications/iTerm.app/"
