---
- hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      
  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      when: configure_homebrew
      tags: ['homebrew']
    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ['dock']

  tasks:
    - import_tasks: tasks/iterm.yml
      when: configure_iterm
      tags: ['iterm']

    # - import_tasks: tasks/dotfiles.yml
    #   when: configure_dotfiles
    #   tags: ['dotfiles']

    # - import_tasks: tasks/config.yml
    #   when: configure_config
    #   tags: ['config']

    # - import_tasks: tasks/keyboard.yml
    #   when: configure_keyboard
    #   tags: ['keyboard']
